extends: airbnb-base
plugins:
  - import
  - jest
rules:
  arrow-body-style: 0
  no-underscore-dangle: 0
  linebreak-style: ["error", "windows"]
  comma-dangle: ["error","always-multiline"]
  # indent: [1, "tab"]
  no-mixed-spaces-and-tabs: ["error", "smart-tabs"]
  no-param-reassign: ["error", { "props": false }]
  "object-shorthand": ["error", "consistent"]
  max-len: ["error", { "code": 150 }]
  "jest/no-disabled-tests": "warn"
  "jest/no-focused-tests": "error"
  "jest/no-identical-title": "error"
  "jest/prefer-to-have-length": "warn"
  "jest/valid-expect": "error"

globals:
  __: true

env:
  "jest/globals": true